### ISSUE TITLE
setting up nao failed

### ISSUE THREAD

**Issue by freealong** [bhuman/BHumanCodeRelease#4]
NAO system version: 2.1.4.13
I follow the instructions on section 2.4 in the coderelease2015 to set up the Nao. Everything goes well during the setting, however  after the robot reboot, it can't find its body.

**Comment by roefer** [comment]
Yes, there seems to be problems with NAOqi 2.1.4.13. There is also a forum thread in Aldebaran's user community about this. It is not certain, whether it has actually anything to do with our code release or just with the update from NAOqi 2.1.2 to 2.1.4. In the forum, some users complaining about this issue do not seem to have anything to do with RoboCup or our code.

Maybe you can post in the forum what you did and which robot version you are using. It would also be interesting to know whether the robot successfully ran NAOqi 2.1.4.13 before you installed the B-Human code or whether you flashed it and then immediately installed B-Human on its first reboot (as our documentations says).

**Comment by freealong** [comment]
Before I installed the B-Human code, the robot successfully ran NAOqi 2.1.4.13.

## original robot's body information:
```
Model Type :  naoH25
Head Version :  VERSION_50
Body Version :  VERSION_50
Laser :  False
Legs :  True
Arms :  True
Extended Arms :  True
Hands :  True
Arm Version :  VERSION_50
Number of Legs :  2
Number of Arms :  2
Number of Hands :  2
```
## After installing B-Human code:
```
Model Type :  naoH21
Head Version :  VERSION_50
Body Version :  VERSION_32
Laser :  False
Legs :  True
Arms :  True
Extended Arms :  False
Hands :  False
Arm Version :  VERSION_32
Number of Legs :  2
Number of Arms :  2
Number of Hands :  0
```

## After installing B-Human code, running Naoqi threw an error:
```
almodelutils: Could not find body version of Nao robot. Falling back to version "VERSION_32"
```
## Does bhuman do anything else to the robot's body besides changing the body's name during the procedure of setting up Nao?

**Comment by roefer** [comment]
No.

**Comment by Zyrin** [comment]
Fixed this problem by using the bodyId to identify the Robot insted of changing the bodyNickName.

**Comment by arezaie14** [comment]
how to set body id on this robots?

**Comment by Zyrin** [comment]
You don not have to set the bodyId. This id is the serial number of the NAO and is embedded in the chestboard of each robot by the manufacturer. The id is just used to associate a name to the robots in a configuration file. This is done via the script addRobotIds in the Install directory. Read section 2.4.2 of the [CodeRelease2015.pdf](https://github.com/bhuman/BHumanCodeRelease/blob/master/CodeRelease2015.pdf) for more details.

**Comment by arezaie14** [comment]
thanks.but we have another problem after reset factory and flashing atom. after flash robot we can not ping to it's ip. what can we do?

**Comment by Zyrin** [comment]
I can not really help you with network problems. That's somethings you have to figure out on your own. I can just tell you, what I do to connect to a NAO after it is freshly flashed, but I assume you do more ore less the same steps: I change my ethernet settings to the ip: 169.254.1.1 (ore something like that. As far as I know the NAO always uses an ip starting with 169.254, if that is not the case change it accordingly) and networkmask: 255.255.0.0. Then I connect my pc to the NAO, wait a few seconds in order for the Robot to acquire its ip and then connect to the ip it says. If that does not work try another pc or operating system?

**Comment by mvafaee** [comment]
We faced the same problem (Error 404: Body Not Found) after installing B-Human code on a NAO ver 5 running naoqi 2.1.4.13.
Here's the Aldebaran's answer:
"It seems that a part of the code modify/erase some body configuration keys.
The only solution is to recover the robot at our repair center in order to resave the body keys (not possible to do that in your side), however, this intervention is not take in charge by the warranty as we are not responsible of the damage caused by the code."

Do you have any suggestion not to send back the robot to Aldebaran center otherwise we would loose a lot of time as well as money?

**Comment by roefer** [comment]
We do not have any suggestions. Since changing the body name was the only change we did in the body, we reasoned that this must be the problem. We have been using the script since 2009 and the commands used were official API before NAOqi 2.0. Actually, the script was provided by Aldebaran at some meeting in early 2009. In NAOqi 2 this API disappeared from the documentation (which we did not realize), but it was still available and continued to work. My guess is that Aldebaran broke that functionality in NAOqi 2.1.4.3, but since they are not using it anymore, they did not realize this. As it is not an official API anymore, the situation is quite unclear.

**Comment by mvn2016** [comment]
In that case downgrading NAOqi from 2.1.4.3 may solve the problem but we have downgraded the NAOqi to earlier versions but the problem remains.

Is there a way to change the body name back to what Aldebaran initially sets?

**Comment by roefer** [comment]
With the error 404, there is no way to communicate with the body.

**Comment by mvn2016** [comment]
So sending back the robot is our only choice?!

**Comment by roefer** [comment]
Yes. Sorry for that, but since we have used this script for more than six years now and it still works most of the time, we could not know that there would be a problem with NAOqi 2.1.4.13 (and we still cannot be sure that it is the reason).

**Comment by mvn2016** [comment]
I wish you could cooperate with Aldebaran to find a fast solution for the problem.

Let me recheck something: the body name is stored in the main controller in the chest and your code has changed it. That's why the head doesn't find it anymore. So Aldebaran should reprogram the chest controller with the correct body name to be found by PC in the head. Am I right?

**Comment by roefer** [comment]
No. We have many robots with changed body names and they all work. Our guess is that Aldebaran's routine overwrote a lot more than just the body name by accident.

**Comment by mvn2016** [comment]
I guess you have not seen and checked a robot with this problem from close.
What about if you kindly take a look at our robot and what goes inside its head remotely by team viewer?

**Comment by roefer** [comment]
We also had such a problem by now. We had to send the robot in for repair.

**Comment by mvn2016** [comment]
That's where Gods failed.
OK, I'm totally convinced that there's no other way. :)

**Comment by mvn2016** [comment]
There's where Gods failed.
OK, I'm totally convinced that there's no other way. :)

**Comment by mvn2016** [comment]
Dear roefer,

Now we have a 2nd healthy nao v5 that want to install bhuman codes on it.
Which release of bhuman codes on which version of naoqi works well and doesn't cause any problem for the robot?
Any special tips?

**Comment by roefer** [comment]
We don't know. Not setting the body name is just an experiment, and we cannot be sure about whether this helps. In the Aldebaran forum, an answer was that it might be bad to shutdown the robot shortly after setting the body name. There it sounds as if waiting for 20 seconds might be safe.

There never were problems with the 2014 code release.

**Comment by arezaie14** [comment]
Hi
What can we do if robot says "Error 404-body not found!" ?

**Comment by roefer** [comment]
Nothing. You can only send it in.

**Comment by to4dy** [comment]
@arezaie14 @mvn2016  Did you manage to solve the problem?

**Comment by roefer** [comment]
The problem of breaking the robots running NAOqi 2.1.4.13 was solved in the beginning of March by not writing to the chestboard anymore. The code release was updated. However, robots that broke can only be fixed by sending them in.
Please note that older code releases still have the problem, as it occurs because of something Aldebaran changed in 2.1.4.13 and not because of something we changed.

**Comment by to4dy** [comment]
@roefer Thanks! We were wondering about this, because the robot in our case is not reacting after reboot, but reflashing made him at least usable again. So it seemed it was fixed :+1:
