### ISSUE TITLE
Creating Project Files / Compiling the Code WINDOWS

### ISSUE THREAD

**Issue by antbono** [bhuman/BHumanCodeRelease#60]
Hello everyone!

I am trying to compile the code in Windows 11 (21H2 version) but it seems the the 'generate.cmd' script does not work properly. If I simply double clik on it, it generates a visual studio solution named 'B-Human' but VisualStudio can't open it (not a valid solution file it reports). Then I tried using the windows terminal and I got the errors you can find in the attachment. 
Am I missing something, or there is a bug actually? 
Thank you all for your attention 

Antonio

P.S. I don't know if it is related but I could not install the 'mold' package as you require in one step of the tutorial.

![err](https://user-images.githubusercontent.com/7023471/200275006-29e596a4-a6e2-4de4-9b31-6a8a1fbdb077.png)

**Comment by roefer** [comment]
Can you please delete your checkout and pull again? Some hidden files were missing.

**Comment by ahasselbring** [comment]
> P.S. I don't know if it is related but I could not install the 'mold' package as you require in one step of the tutorial.

This is likely related to the Ubuntu version in the WSL. The new code release requires Ubuntu 22.04 in the WSL (it seems that this still can be installed only from the Microsoft Store, but will become the default WSL distribution soon: https://github.com/microsoft/WSL/commit/4025b656b6d93e4ce51abf375b06c7547ac2a0ac)

**Comment by antbono** [comment]
Thank you @roefer for the new commit  (new files added files in  Make/Linux/...  subfolders  ). I pulled it but nothing changed unfortunately...

-----

@ahasselbring I have the 22.04 version in my WSL 

![err](https://user-images.githubusercontent.com/7023471/200289215-f24c0fdc-02da-4c37-8e91-a1e1d2e7590f.png)

**Comment by ahasselbring** [comment]
You actually have to delete and clone the repository. Pulling does not help, git will not change the line endings of existing files otherwise.

Did you run `apt update` in WSL?

**Comment by antbono** [comment]
I forgot to run 'update' after choosin Ubuntu 22.04 as default distro in wsl, now the package is found correctly. Sorry for the mistake...

I cloned the repository again and now Visual Studio can read the generated solution file. It compiles the project too with simRobot as target.

I don't know if it is important but I had these warnings/errors when calling the generate command. 

Thank you again for your collaboration!

![err](https://user-images.githubusercontent.com/7023471/200301728-dd1ab85d-e46a-4a71-bd54-500274861ab3.png)

**Comment by ahasselbring** [comment]
I can't tell exactly because I don't know how you created that Ubuntu 22.04 instance, but something about the WSL setup isn't right. Normally, cmake (it's required in the WSL too in order to be able to compile for the real robot) is installed by the command
```
wsl apt -y install astyle ccache clang cmake llvm mold net-tools ninja-build pigz rsync xxd
```
that is given in [here](https://wiki.b-human.de/coderelease2022/getting-started/#setting-up-the-development-computer). Maybe you ran that command before setting the default to 22.04, such that the packages are installed in the other instance? Anyway, rerunning that `apt install` line in the correct WSL instance should fix the problem with the next run of `generate`, so you would be able to compile for the NAO.

(During the installation, you might get error messages that are due to [this WSL bug](https://github.com/microsoft/WSL/issues/8219))
