### ISSUE TITLE
nao robot v4

### ISSUE THREAD

**Issue by RezaAndizyan** [bhuman/BHumanCodeRelease#72]
can i use this codes for my nao robots in robocup?
can you help me?

**Comment by ahasselbring** [comment]
I don't know what exactly the question is, but all B-Human code releases since 2019 support exclusively NAO 6.

**Comment by RezaAndizyan** [comment]
i have NAO 4 and i downloaded code release 2015, so i think its ok  to  run this codes.
but i dont know  can i use this codes  in robocup?

**Comment by roefer** [comment]
The code is more than seven years old. A lot has changed in the Standard Platform League since then. You would have to re-implement large parts of the system, e.g. detecting the black and white ball, handling dynamic lighting, limited communication, etc. In addition, the NAO 4 is seven years older than the NAO 6 everybody else uses (e.g. single core vs. quad core processor). I am not sure whether Aldebaran would still offer to repair these robots.

In general, we only answer questions about our current code release.
