### ISSUE TITLE
Search for the substitute of Activity.cpp in BehaviorStatus

### ISSUE THREAD

**Issue by infCraft** [bhuman/BHumanCodeRelease#85]
We are conducting our code using BHuman 2023 code release, but when transforming our code from code release 2022, we found that the Activity.cpp in folder \Src\Modules\BehaviorControl\SkillBehaviorControl\Skills\Output\BehaviorStatus\Activity.cpp was deleted. Also, in the code release 2022, we found that in the Src/Representations/BehaviorControl
/BehaviorStatus.h there was a enum including Activities, which didn't appear in the same file in code release 2023. Nevertheless, we need to use Activity for communication between robots. What is the substitute of the Activity in 2023?
Thanks for your reply!

**Comment by ahasselbring** [comment]
There is no direct replacement (technically, its replacement is `calibrationFinished`, because that is the only thing we used the `activity` for). If you still need to communicate something like an activity in the `BehaviorStatus`, I suggest to undo the changes from 2022 to 2023 related to `BehaviorStatus`. Note that in order to be communicated, `activity` must appear in `Config/Scenarios/Default/teamMessage.def` and probably in `TeamMessageHandler::behaviorStatusChanged`.
